// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/56295f5058cac7ae458540423c50ac2dcf9fc711/path-exists/path-exists.d.ts
// Type definitions for path-exists 1.0.0
// Project: https://github.com/sindresorhus/path-exists
// Definitions by: Shogo Iwano <https://github.com/shiwano>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped

declare module "path-exists" {
    interface PathExists {
        (path: string, callback: (error: Error, exists: boolean) => void): void;
        sync(path: string): boolean;
    }

    var pathExists: PathExists;
    export = pathExists;
}