// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/56295f5058cac7ae458540423c50ac2dcf9fc711/gulp-mocha/gulp-mocha.d.ts
// Type definitions for gulp-mocha
// Project: https://github.com/sindresorhus/gulp-mocha
// Definitions by: Asana <https://asana.com>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped


declare module "gulp-mocha" {
    function mocha(setupOptions?: MochaSetupOptions): NodeJS.ReadWriteStream;
    namespace mocha {}
    export = mocha;
}